[proj-datumgrid]
git-tree-sha1 = "aacba15828c4e6c6ec476994b19aa36f63a7f31a"
lazy = true

    [[proj-datumgrid.download]]
    sha256 = "3ff6618a0acc9f0b9b4f6a62e7ff0f7bf538fb4f74de47ad04da1317408fcc15"
    url = "https://github.com/OSGeo/proj-datumgrid/releases/download/1.8/proj-datumgrid-1.8.tar.gz"
    [[proj-datumgrid.download]]
    sha256 = "3ff6618a0acc9f0b9b4f6a62e7ff0f7bf538fb4f74de47ad04da1317408fcc15"
    url = "https://download.osgeo.org/proj/proj-datumgrid-1.8.tar.gz"

[proj-datumgrid-europe]
git-tree-sha1 = "512736c93799a9b0c3e73f9e63af81749e4c56e2"
lazy = true

    [[proj-datumgrid-europe.download]]
    sha256 = "af2f4f364d84eb9d5ca23403f8540ae8daee54ec900903bc92d48afb1ed285f8"
    url = "https://github.com/OSGeo/proj-datumgrid/releases/download/europe-1.6/proj-datumgrid-europe-1.6.tar.gz"
    [[proj-datumgrid-europe.download]]
    sha256 = "af2f4f364d84eb9d5ca23403f8540ae8daee54ec900903bc92d48afb1ed285f8"
    url = "https://download.osgeo.org/proj/proj-datumgrid-europe-1.6.tar.gz"

[proj-datumgrid-north-america]
git-tree-sha1 = "ee77031eb3ef02277e2da0c0f66ea710f51b769d"
lazy = true

    [[proj-datumgrid-north-america.download]]
    sha256 = "95a6cdcdc078caed412ea66d3fdd2f699286336d5ca6c98bffb2d7132585ce40"
    url = "https://github.com/OSGeo/proj-datumgrid/releases/download/north-america-1.4/proj-datumgrid-north-america-1.4.tar.gz"
    [[proj-datumgrid-north-america.download]]
    sha256 = "95a6cdcdc078caed412ea66d3fdd2f699286336d5ca6c98bffb2d7132585ce40"
    url = "https://download.osgeo.org/proj/proj-datumgrid-north-america-1.4.tar.gz"

[proj-datumgrid-oceania]
git-tree-sha1 = "17fe438b3184182d90ff4c9df2d8b55c393d45c9"
lazy = true

    [[proj-datumgrid-oceania.download]]
    sha256 = "952c43886c9ed6a098c308de61161a00cbe83fbb0f6e9e43c0c25c323bb06a4c"
    url = "https://github.com/OSGeo/proj-datumgrid/releases/download/oceania-1.2/proj-datumgrid-oceania-1.2.tar.gz"
    [[proj-datumgrid-oceania.download]]
    sha256 = "952c43886c9ed6a098c308de61161a00cbe83fbb0f6e9e43c0c25c323bb06a4c"
    url = "https://download.osgeo.org/proj/proj-datumgrid-oceania-1.2.tar.gz"

[proj-datumgrid-world]
git-tree-sha1 = "4db21264437234e406cf3e6c6dbc93762fbde886"
lazy = true

    [[proj-datumgrid-world.download]]
    sha256 = "a488a5a69d1af6ec2ee83a2c64c52adac52e6dbfafe883f0341340009a9f40ba"
    url = "https://github.com/OSGeo/proj-datumgrid/releases/download/world-1.0/proj-datumgrid-world-1.0.tar.gz"
    [[proj-datumgrid-world.download]]
    sha256 = "a488a5a69d1af6ec2ee83a2c64c52adac52e6dbfafe883f0341340009a9f40ba"
    url = "https://download.osgeo.org/proj/proj-datumgrid-world-1.0.tar.gz"
